### ISSUE TITLE
Crashing on large gifs

### ISSUE THREAD

**Issue by perlatus** [perlatus/e1547#45]
Likely due to running out of memory, since it only happens on my low-end test device.

#1

**Comment by sakhavhyand** [comment]
I have discovered the same problem today on my OnePlus 5T. I don't think it comes from low memory, i'm far to be full with my 8GB.

**Comment by Smethan** [comment]
I would like to add to this. I think the crash comes from not unloading gifs after swiping through them. I was able to reproduce this on an ipad 2017, an iPhone XR, and an iPhone 7 by searching for gifs with the tag type:gif and swiping through them. After swiping through about 7 - 15 the app would be killed by ios due to too much memory being used. A temporary workaround is to return to the grid view every few gifs to free the memory. I'll see if I can figure out a good loading/unloading solution and make a PR
